spring:
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 127.0.0.1:18848 # Nacos 服务器地址
        namespace: 489c83d3-b3c4-4c6a-9677- 45065fc2f80a # Nacos 命名空间 uat 的编号